version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  server: # TODO: Rename to app
    image: node:20
    container_name: server
    command: sh -c "npm install && npm run dev"
    ports:
      - 5001:5001
    working_dir: /server
    env_file: .env
    environment:
      - PORT=5001
    volumes:
      - ./:/server
    depends_on:
      - redis
      - influxdb

volumes:
  influxdb-data:
  grafana-data:
  redis-data:
