{
 "title": "Realtime Frontend Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "users",
    "label": "Users",
    "query": "import \"influxdata/influxdb/v1\"\n\nuserList = v1.tagValues(\n  bucket: \"fps\",\n  tag: \"user\",\n  predicate: (r) => true,\n  start: -24h\n)\n\nusers = from(bucket: \"fps\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fps\")\n  |> keep(columns: [\"user\"])\n  |> distinct(column: \"user\")\n  |> yield(name: \"distinct_users\")"
   }
  ]
 },
 "panels": [
  { "title": "User $users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "users" },
  {
   "title": "FPS and Events",
   "type": "timeseries",
   "description": "Displays the FPS data over time for all or selected users and the events that happened",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"fps\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fps\")\n  |> filter(fn: (r) => contains(value: r[\"user\"], set: [\"${users:json}\"]))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    },
    {
     "query": "from(bucket: \"fps\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] != \"fps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => contains(value: r[\"user\"], set: [\"${users:json}\"]))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"fps\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"visibility_change\")\n  |> filter(fn: (r) => r[\"_field\"] == \"isVisible\")\n  |> filter(fn: (r) => contains(value: r[\"user\"], set: [\"${users:json}\"]))\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: true)\n  |> fill(usePrevious: true)"
    }
   ]
  },
  {
   "title": "Mean FPS",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fps\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fps\")\n  |> filter(fn: (r) => contains(value: r[\"user\"], set: [\"${users:json}\"]))\n  |> group(columns: [\"user\"])\n  |> mean(column: \"_value\")\n  |> group()\n  |> mean(column: \"_value\")\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "P99 FPS",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"fps\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fps\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fps\")\n  |> filter(fn: (r) => contains(value: r[\"user\"], set: [\"${users:json}\"]))\n  |> group(columns: [\"user\"])\n  |> quantile(column: \"_value\", q: 0.99)\n  |> yield(name: \"p99\")\n"
    }
   ]
  }
 ]
}